apiVersion: v1
kind: Service
metadata:
  name: poc-nginx
spec:
  selector:
    app: poc-nginx
  ports:
  - port: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-nginx
  labels:
    app: poc-nginx
spec:
  replicas: 1
  template:
    metadata:
      name: poc-nginx
      labels:
        app: poc-nginx
    spec:
      containers:
      - name: poc-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: poc-nginx