apiVersion: v1
kind: PersistentVolume
metadata:
  name: poc-pv-1
  labels:
    type : local
spec:
  storageClassName: manual
  capacity:
    storage : 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mtn/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: poc-pv-2
  labels:
    type : local
spec:
  storageClassName: manual
  capacity:
    storage : 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mtn/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poc-wordpress-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage : 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poc-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage : 1Gi